<?php
session_start();

// Check if the user is logged in and is an admin
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../login.php?error=unauthorized_access");
    exit();
}

// Welcome message with admin's name (if available in session)
$admin_name = isset($_SESSION['admin_name']) ? $_SESSION['admin_name'] : 'Admin';
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/style.css">
    <title>Admin Dashboard - Hospital Management System</title>
</head>
<body>

    <!-- Main container -->
    <div class="container">
        <!-- Header -->
        <header>
            <h1>Admin Dashboard</h1>
            <p>Welcome, <?php echo htmlspecialchars($admin_name); ?>! How can we assist you today?</p>
        </header>

        <!-- Navigation Menu -->
        <nav>
            <ul>
                <li><a href="manage_doctors.php">Manage Doctors</a></li>
                <li><a href="manage_patients.php">Manage Patients</a></li>
                <li><a href="manage_appointments.php">Manage Appointments</a></li>
                <li><a href="reports.php">View Reports</a></li>
                <li><a href="settings.php">Settings</a></li>
                <li><a href="logout.php">Logout</a></li>
            </ul>
        </nav>

        <!-- Dashboard Content Section -->
        <section>
            <h1>Hospital Operations Management</h1>
            <p>This dashboard allows you to manage all hospital operations seamlessly. Use the menu above to navigate between different sections.</p>
            
            <div class="action-item">
    <h3>Manage Patients</h3>
    <p>Efficiently manage patient records, update patient details, and monitor ongoing treatment plans. Use this section to:</p>
    <ul>
        <li><strong>Register New Patients:</strong> Add new patient records, including personal information, medical history, and insurance details.</li>
        <li><strong>Update Patient Profiles:</strong> Modify existing patient data such as contact information, current medications, or diagnosis reports.</li>
        <li><strong>Track Treatment History:</strong> Review and update patients' medical history, including diagnosis, prescribed medications, and procedures.</li>
        <li><strong>Discharge Patients:</strong> Complete the discharge process by marking patients as discharged and generating final reports.</li>
    </ul>
    <p>Click <a href="manage_patients.php">here</a> to access the patient management system.</p>
</div>

              
<div class="action-item">
    <h3>Manage Appointments</h3>
    <p>Effectively manage patient appointments and doctor schedules with the appointment management system. You can:</p>
    <ul>
        <li><strong>Schedule New Appointments:</strong> Book new appointments based on doctor availability, patient preferences, and urgency. Ensure accurate time slot management.</li>
        <li><strong>View Upcoming Appointments:</strong> View all scheduled appointments for doctors and patients. Filter appointments by date, department, or patient name for easier navigation.</li>
        <li><strong>Cancel or Reschedule Appointments:</strong> Modify existing appointments by canceling or rescheduling them according to patient or doctor requirements. Automatic notifications are sent for any changes.</li>
        <li><strong>Appointment Reminders:</strong> Automatically generate and send appointment reminders to patients via SMS or email, reducing no-shows and improving hospital efficiency.</li>
        <li><strong>Track Appointment History:</strong> View the history of past appointments, including date, time, doctor, and purpose of visit. This helps maintain a detailed patient treatment record.</li>
    </ul>
    <p>Click <a href="manage_appointments.php">here</a> to manage patient appointments efficiently.</p>
</div>
<div class="action-item">
    <h3>Reports and Analytics</h3>
    <p>Gain insights into hospital performance and make data-driven decisions with our reporting and analytics tools. This section allows you to:</p>
    <ul>
        <li><strong>Generate Treatment Reports:</strong> Create detailed reports of patient treatments, including diagnoses, prescribed medications, procedures, and recovery statistics.</li>
        <li><strong>Doctor Performance Analytics:</strong> Analyze doctor performance based on metrics such as patient outcomes, number of consultations, and feedback ratings.</li>
        <li><strong>Hospital Occupancy Reports:</strong> View reports on hospital bed occupancy rates, available resources, and patient flow. Use this data to optimize operations.</li>
        <li><strong>Revenue and Billing Reports:</strong> Generate financial reports showing revenue generated by departments, services, and billing categories. Get a clear view of hospital income and expenses.</li>
        <li><strong>Customizable Dashboards:</strong> Build custom dashboards to view key performance indicators (KPIs) such as patient satisfaction, appointment no-show rates, and resource utilization.</li>
        <li><strong>Export Data:</strong> Export reports and data to CSV or PDF formats for further analysis or to share with relevant stakeholders.</li>
    </ul>
    <p>Click <a href="reports.php">here</a> to generate and analyze hospital performance reports.</p>
</div>

                <div class="action-item">
    <h3>System Settings</h3>
    <p>Manage and configure the system to ensure smooth operations across all departments. The settings section provides options for:</p>
    <ul>
        <li><strong>User Management:</strong> Add, remove, or update user roles (e.g., doctors, nurses, admins). Assign permissions and access rights based on the role and department.</li>
        <li><strong>Security Settings:</strong> Configure security features, such as password policies, two-factor authentication, and session timeouts, to ensure data safety and privacy.</li>
        <li><strong>Notification Settings:</strong> Manage notification preferences for appointment reminders, system alerts, and patient follow-ups via email or SMS.</li>
        <li><strong>Backup and Data Recovery:</strong> Schedule regular data backups and configure recovery options to ensure that patient data is never lost in case of system failure.</li>
        <li><strong>Database Management:</strong> Optimize and manage the hospital database, including patient records, appointment logs, and financial data. Maintain clean and accurate data by implementing automatic cleanup routines.</li>
        <li><strong>System Customization:</strong> Customize the system interface, language settings, and time zones to meet the hospital's operational preferences.</li>
        <li><strong>Audit Logs:</strong> Monitor system activities and maintain an audit trail of user actions, helping track changes and ensuring accountability.</li>
    </ul>
    <p>Click <a href="settings.php">here</a> to configure system preferences and manage user access.</p>
</div>

            </div>
        </section>
    </div>

    <!-- Footer -->
    <footer>
        <div class="container">
            <p>&copy; 2024 Hospital Management System. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>

